### ISSUE TITLE
Could you help me?

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/JaydenDev#1]
I need beta testers for a NodeJS client I made for SpellCheckJS. Could you see how it works and give me suggestions?

**Comment by jdev082** [comment]
@webdev03 not the right place to report software bugs

**Comment by imdevarsh** [comment]
@JaydenDev what is the use of pinging me here?!?!?!

**Comment by jdev082** [comment]
> @JaydenDev what is the use of pinging me here?!?!?!

sorry i was rushing to tell people not to make issues on this repo

**Comment by imdevarsh** [comment]
It's to contact you!

**Comment by jdev082** [comment]
@webdev03 why would you want to?

**Comment by hello-smile6** [comment]
> @webdev03 not the right place to report software bugs

@JaydenDev Did you make a bot that says that?

**Comment by jdev082** [comment]
@hello-smile6 no i posted it myself.
